### ISSUE TITLE
Sprint 3 - Criação do documento de arquitetura

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#10]
# Descrição
Esta issue visa a criação do documento de arquitetura

# Tarefas
- [x] Selecionar templates que possam ser utilizados.
- [x] Criação da primeira versão do documento de arquitetura.

# Critérios de aceitação
- [x] Primeira versão do documento criada.

**Comment by jpanacleto2** [comment]
Foi verificado a primeira versão do documento de arquitetura estando tudo de acordo.
