### ISSUE TITLE
Sprint 3 - Definição de ferramentas de front-end

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#14]
# Descrição
Esta issue visa a pesquisa e seleção das ferramentas de front-end que podem ser utilizadas para o desenvolvimento do projeto.

# Tarefas
- [x] Pesquisar ferramentas de frotn-end que atendam o projeto.
- [x] Listar ferramentas que podem/serão usadas.

# Critérios de aceitação
- [x] As ferramentas devem estar listadas.
- [x] Deve ter sido selecionada ao menos uma ferramenta para ser utilizada no desenvolvimento do front-end.

**Comment by jpanacleto2** [comment]
# Ferramentas

1. HTML 5
2. CSS
3. Metabase
4. Bootstrap
