### ISSUE TITLE
Sprint 3 - Treinamento python 

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#15]
# Descrição
Python será uma linguagem usada extensivamente no projeto, esta issue visa treinar os membros para ter a capacidade de programação nesta linguagem.

# Tarefas
- [x] Treinamento de como programar em python.
- [x] Exemplo de um programa simples.

# Critérios de aceitação
- [x] Todos os membros devem ter realizado o exemplo disponibilizado.
- [x] O exemplo deve ser disponibilizado no comentário desta issue.

**Comment by jpanacleto2** [comment]
# Videos para o treinamento Python voltado ao WebScrapping

1. https://www.youtube.com/watch?v=ctcDfKYrzOQ
2. https://www.youtube.com/watch?v=j6B8shHXzks
3. https://www.youtube.com/watch?v=Vxl5jUltHBo
