### ISSUE TITLE
Sprint 5 - Abertura do git pages

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#17]
# Descrição
Issue destinada para o início do desenvolvimento do git pages do projeto

# Tarefas
- [x] Definir um template a ser seguido.
- [x] Primeira versão do git pages.

# Critérios de aceitação
- [x] Primeira versão do git pages funcionando.

**Comment by pabloheika** [comment]
A pagina foi feita e esta disponível.
