### ISSUE TITLE
Sprint 4 - Estudo do Metabase

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#19]
# Descrição
Issue destinada ao estudo do metabase, ferramenta de BI que será de suma importância para o desenvolvimento do projeto

# Tarefas
- [x] Criar um novo projeto no metabase.
- [x] Criar um dashboard de exemplo no metabase (utilizando filtros).
- [x] Detalhar nos comentários desta issue como realizar as tarefas acima.

# Critérios de aceitação
- [x] Dashboard criado.
- [x] Passo a Passo disponível no comentário da issue.

**Comment by Eruel6** [comment]
## Como criar um dashboard

1 -> na pagina do metabase na seção de "our analitics" clique em "browse all items" para abrir a visão de todos os dashboards

2 -> para criar um novo dashboard clique no "+" no canto superior direito da pagina e selecione a opção question

3 -> quando entrar na pagina inicial da criação das questions, selecione o banco de dados a ser utilizado.

4 -> após entrar na pagina de criação da question no campo data o dado a ser trabalhado ( ex pessoa, review...)

5 -> quando selecionado o dado basta adicionar os filtros pertinentes.

6 -> na parte de sumarize escolha o dado que gostaria de ver

7 -> após tudo feito clique em vizualise, se os dados estiverem aparecendo de forma correta, basta clicar para adicionar em um dashboard ou criar um novo.

**Comment by Eruel6** [comment]
## vídeo explicativo de como utilizar o metabase

[Vídeo](https://www.youtube.com/watch?v=4bNp906oOhs) em inglês de como utilizar o metabase desde funções mais básicas até funções complexas

**Comment by jpanacleto2** [comment]
Todas as tarefas e criterios de aceitação foram completadas.
