### ISSUE TITLE
Sprint 2 - Estudo do documento de arquitetura

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#2]
# Descrição
Deve ser estudado como é feito um documento de arquitetura através da visualização dos documentos dos grupos passados.

# Tarefas
- [x] Estudar o documento de arquitetura.
- [x] Informar os demais membros sobre o que é o documento.

# Critérios de aceitação
- [x] Explicar para o grupo.

**Comment by Thiab394** [comment]
### Documento de Arquitetura
O documento de arquitetura, consiste em um documento onde serão listadas todas as tecnologias utilizadas para a realização adequada do projeto, também serve como um meio de comunicação entre o(s) arquiteto(s) e o restante dos membros do time, também possui visões, tanto obrigatórias quanto opcionais, como a visão de casos de uso(explicada mais a baixo) e a visão logica , também podendo implementar visão de processas,dados, visão de implementação, entre outras. mostradas nesse link: [https://www.cin.ufpe.br/~gta/rup-vc/core.base_rup/workproducts/rup_software_architecture_document_C367485C.html#:~:text=O%20documento%20de%20arquitetura%20de,significativas%20tomadas%20sobre%20o%20projeto.](url)
Também contendo coisas básicas como a introdução, contendo o objetivo e o escopo do projeto, a representação arquitetural que seria a própria listagem das tecnologias e o que seriam elas e também as metas e restrições arquiteturais, relacionadas ás próprias tecnologias.

### Visões
**Visão de casos de uso**
- Consiste na listagem dos casos de uso(utilização) do projeto, ou seja, o que seria necessário para o projeto funcionar, e quais casos podem ocorrer/devem ocorrer, e também que são esperados de acontecer.
- Contem os possíveis atores do projeto, como líder, voluntario, etc.
- Contem as prioridades de cada caso de uso individualmente, e se eles são funcionais ou não funcionais.

**Visão lógica**

Visão geral:
- A visão lógica geral consiste na listagem das tecnologias á serem utilizadas para realização do projeto, como seriam as interações entre elas, e como ficaria todo o processo, até o projeto estar concluído, incluindo a participação de usuários externos, internos, bots, entre outros.

Diagrama de pacotes:
- consiste em um diagrama com a listagem de maneira mais visual das tecnologias utilizadas, mostrando como funcionaria o backend e o frontend do projeto, como exemplo temos o do projeto acácia no link a seguir: [https://github.com/fga-eps-mds/2019.2-Acacia/blob/develop/docs/architecture_document.md#52-diagrama-de-pacotes](url)

informações retiradas do site mostrado acima e no documento de arquitetura do projeto acácia, caso queiram olhar com mais detalhes: [https://github.com/fga-eps-mds/2019.2-Acacia/blob/develop/docs/architecture_document.md#documento-de-arquitetura](url)
