### ISSUE TITLE
Sprint 4 -  Criação do documento "como contribuir"

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#21]
# Descrição
Criação do documento de diretrizes para auxiliar pessoas de fora do grupo original de desenvolvimento de como contribuir com o projeto.

# Tarefas
- [x] Estudar os documentos de como contribuir dos semestres passados.
- [x] Selecionar um template para seguir.
- [x] Fazer o documento de como contribuir.

# Critérios de aceitação
- [x] Documento feito e disponível no repositório.

**Comment by jpanacleto2** [comment]
Template criado com texto sobre como contribuir com nosso projeto.

**Comment by Eruel6** [comment]
Documento criado de acordo com o definido com o grupo e disponibilizado no repositório. [Como Contribuir](https://github.com/fga-eps-mds/2022-1-OiaAMoeda/blob/main/Docs/Como_contribuir.md)
