### ISSUE TITLE
Sprint 4 - Criação de um template para "Pull Request"

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#23]
# Descrição
A fim de padronizar os pulls requests realizados no repositório, criar um template para ser seguido por membros do projeto e por novos contribuidores.

# Tarefas
- [x] Estudar os templates de pull resquest dos semestres anteriores.
- [x] Selecionar um template para ser seguido.
- [x] Criação do template de pull request.

# Critérios de aceitação
- [x] Documento criado.

**Comment by Thiab394** [comment]
template de pull request refatorada para ficar mais de acordo com seu proposito.

**Comment by Eruel6** [comment]
Pull request template criado e disponível [aqui](https://github.com/fga-eps-mds/2022-1-OiaAMoeda/blob/main/pull_request_template.md)
