### ISSUE TITLE
Sprint 4 - Finalizar o backlog do projeto

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#24]
# Descrição
Falta ainda um pouco de refino no backlog do projeto, esta issue se destina a finalização de qualquer pendência existente em relação ao backlog e um polimento do mesmo.

# Tarefas
- [x] Terminar os épicos e features do backlog.
- [x] Terminar as histórias de usuário.

# Critérios de aceitação
- [x] Backlog finalizado.
- [x] Backlog disponível no repositório.

**Comment by jpanacleto2** [comment]
Foi finalizado a primeira versão do Product Backlog e esta disponivel na pasta docs

**Comment by Eruel6** [comment]
Backlog de acordo com o que o time definiu do projeto
