### ISSUE TITLE
Sprint 5 - Criação Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by yagompassos** [fga-eps-mds/2022-1-OiaAMoeda#28]
# Descrição
Definir o protótipo de alta prioridade do produto no FIGMA

# Tarefas
- [x] Criar arquivo do FIGMA
- [x] Gerar as telas do escopo
- [x] Estilizar as paginas de acordo com o gosto da equipe
- [x] Mostrar como as funcionalidades vão parecer

# Critérios de aceitação
- [x] Todas as telas estão criadas
- [x] A equipe está de acordo com a estilização
- [x] O protótipo demonstra e exemplifica as funcionalidades

**Comment by jpanacleto2** [comment]
Foi criado o prototipo de alta fidelidade  e disponobilizado a todos na pasta de docs
