### ISSUE TITLE
Sprint 5 - Criação da identidade visual

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#30]
# Descrição
Esta issue tem por objetivo definir a identidade visual do projeto, para facilitar o desenvolvimento do front end e também a colaboração com o front caso ocorra.

# Tarefas
- [x] Definir fonte a ser usada no projeto.
- [x] Definir paleta de cores do projeto.
- [x] Fazer um documento com as eecolhas.

# Critérios de aceitação
- [ ] Documento deve estar disponível na área de documentos do repositório.

**Comment by yagompassos** [comment]
Fala grupo, me dei assignee pra essa issue pois gostaria de contribuir nas decisões das características do nosso site. Seria legal se mais de vocês se encarregassem dessa issue também. Aguardo as ideias aqui para poder opinar.

**Comment by pabloheika** [comment]
Esboço para ser decidido uma nova cor que dever ser adicionada ao trabalho especificamente para contrastar com a logo.
Até então existem três cores já definidas a serem usadas no projeto pois estão presentes na logo, são elas:
Marrom: #7e5746
Amarelo:#ffc107
Cinza:#3f3f3f
As cores pretas e branca também já estão no projeto.
As cores definidas nesse esboço são Cores complementares e triádicas das presentes na logo para ter um contraste melhor definido.
![image](https://user-images.githubusercontent.com/45216323/180636800-f6ca6cfa-de61-469e-8769-65493838e145.png)

**Comment by pabloheika** [comment]
# Votação para definir a cor.
> vote reagindo e esse comentário.

- 👍 Sem nova cor a logo dever ser posta apenas sobre o branco, preto e cinza.
- 😄 Quarta cor(azul).
- 🎉 Quinta cor(roxo).
- 😕 Sexta cor(verde).
- ❤️ Sétima cor(violeta).
- 👀 Oitava e ultima cor(ciano?).
