### ISSUE TITLE
Sprint 5 - Atualização dos documentos

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#31]
# Descrição
Com a refatoração do escopo, alguns documentos ficaram errados, esta issue tem por objetivo corrigir estes problemas além de adicionar alguns diagramas necessários aos documentos.

# Tarefas
- [x] Corrigir documentos.
- [x] Adicionar novos diagramas que sejam necessários à algum documento.

# Critérios de aceitação
- [x] Documentos corrigidos na área de documentos do github.

**Comment by Osidious** [comment]
Fiz pequenas correções aos documentos:
- Backlog do Produto
- Código de Conduta
- Como Contribuir
- Documento de Arquitetura 
- Documento de Requisitos
- Documento de Visão
- Termo de Abertura

Também adicionei o histórico de versões ao Código de Conduta.

**Comment by Eruel6** [comment]
Adicionado os tópicos 6,7 e 8 que faltavam ao termo de abertura do projeto

**Comment by jpanacleto2** [comment]
Foram adicionados as tecnologias que utilizaremos e os diagramas no documento de arquitetura

**Comment by Eruel6** [comment]
Documentos revisados
