### ISSUE TITLE
Sprint 6 - Padronização dos ambientes de trabalho

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#32]
# Descrição
Uma parte importante de trabalhar em equipe é a capacidade de todos os membros conseguirem se ajudar, para isso os ambientes de trabalho precisam ser compatíveis, esta issue tem o objetivo de padroniar estes ambientes.

# Tarefas
- [x] Configurar o ambiente de trabalho.

# Critérios de aceitação
- [x] Todos os membros devem ter o ambiente de trabalho configurado.

**Comment by yagompassos** [comment]
O arquivo README.md foi atualizado com as instruções de como configurar o ambiente de trabalho.
Verifiquem as mudanças e apliquem nas suas máquinas. Marquem a caixinha quando estiverem sem dúvidas e com as máquinas configuradas de acordo com o desenvolvimento do projeto.

Eu estou com meu ambiente de trabalho configurado de acordo com as instruções da README.md
- [x] @Eruel6 
- [x] @yagompassos
- [x] @Thiab394 
- [x] @jpanacleto2 
- [x] @Osidious 
- [x] @JoaoGElvas 
- [x] @pabloheika 
- [x] @Silas-neres
