### ISSUE TITLE
Sprint 5 - Atualizar o readme do projeto

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#33]
# Descrição
O readme do projeto é de suma importância para novos colaboradores, esta issue tem por objetivo atualizar esta parte do repositório para tornar mais fácil a colaboração e o entendimento sobre o projeto.

# Tarefas
- [x] Texto do Readme do projeto atualizado.
- [x] Link para o código de conduta.
- [x] Link para o documento de como contribuir.

# Critérios de aceitação
- [x] Readme atualizado.

**Comment by Thiab394** [comment]
Readme do projeto adicionado, aguardando revisão do pull request

**Comment by Eruel6** [comment]
Pull request revisado e aceito
