### ISSUE TITLE
Sprint 6 - Criação do logotipo

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#34]
# Descrição
A logotipo é parte importante para identificação do projeto, esta issue tem por objetivo a criação deste artefato.

# Tarefas
- [x] Criar o logotipo do projeto.
- [x] Adicionar o logo no gitpages.

# Critérios de aceitação
- [x] Logotipo disponível no repositório para ser utilizado no projeto.

**Comment by pabloheika** [comment]
Rascunho para decidir elementos e formatos da logo.

![photo_2022-07-16_20-05-15](https://user-images.githubusercontent.com/45216323/179374547-780a8233-0237-48bb-8c1a-61f2afd66732.jpg)

**Comment by pabloheika** [comment]
Na imagem acima estão os seguintes exemplos para serem definidos:

1. Tipo de borda da moeda 
2. Impressão da moeda (se escolherem capivara coin o terceiro ponto é descartado.)
3. Capivara out ou não.

votação por reações nos comentários abaixo.
*As cores não refletem o resultado final.

**Comment by pabloheika** [comment]
1. Votação tipo de borda da moeda

- 👍 Borda 1 Real (material e cores da moeda são diferentes).
- 😄 Borda padrão (feita em relevo  no próprio material, tipo 50 centavos de real.)
- 🎉 Sem borda.

**Comment by pabloheika** [comment]
2. Votação impressão da moeda (se escolherem capivara coin o terceiro ponto é descartado.)

- 👍 Sem impressão.
- 😄 Olho de Hórus.
- 🎉 "C" de criptomoeda.
- 😕 Capivara coin.

**Comment by pabloheika** [comment]
3. Votação Capivara out ou não.

- 👍 Sem capivara out.
- 😄 Capivara na frente da moeda.
- 🎉 Capivara sentada na moeda.
- 😕 Votei em "Capivara coin" no ponto 2.

**Comment by pabloheika** [comment]
Issue concluída aguardando revisão.
