### ISSUE TITLE
Sprint 6 - Política de Branches

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#38]
# Descrição
Para facilitar a colaboração com o projeto os colaboradores devem saber como funcionam as branches do mesmo.

# Tarefas
- [x] Estudar políticas de branches de grupos dos semestres passados.
- [x] Criar a política de branches do projeto

# Critérios de aceitação
- [x] Política de branches criadas e disponível.
- [x] Acessível pelo documento de como contribuir.

**Comment by Silas-neres** [comment]
alguém revisa a política de branches, já adcionei lá em docs

**Comment by Eruel6** [comment]
A politica de branches esta de acordo com o definido pelo grupo
