### ISSUE TITLE
Sprint 6 - Revisão do backlog do produto

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#40]
# Descrição
Durante o sprint planning foram notados alguns erros presentes no backlog do produto, esta issue visa resolver os mesmos.

# Tarefas
- [x] Revisar o backlog do produto.

# Critérios de aceitação
- [x] Backlog consistente com o projeto.
- [x] Sem user stories repetidas.

**Comment by Thiab394** [comment]
O Backlog do produto foi revisado por todos, e alterado de maneira á ficar mais compreensível e alinhado com as ambições do grupo  para o projeto
