### ISSUE TITLE
Sprint 7 - Revisão do documento de arquitetura

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#43]
# Descrição
Revisar o documento de arquitetura, com melhorias nos diagramas, e possíveis correções nas tecnologias utilizadas;

# Tarefas
- [x] Revisar o documento.
- [x] Revisar o diagrama de pacotes.
- [x] Verificar as tecnologias utilizadas.

# Critérios de aceitação
- [x] Documento revisado.

**Comment by Thiab394** [comment]
O Documento de arquitetura está de acordo com o escopo, o backlog e as tecnologias utilizadas para realização do projeto
