### ISSUE TITLE
Sprint 7 - revisão do EAP 

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#45]
# Descrição
Com a mudança de escopo que ocorreu no decorrer do projeto, a EAP criada ficou fora do escopo, por isso será necessário revisar o documento.

# Tarefas
- [x] Reorganizar a EAP de acordo com o novo escopo do projeto.

# Critérios de aceitação
- [x] Documento revisado.

**Comment by pabloheika** [comment]
A documentação foi revisada e está tudo de acordo.
