### ISSUE TITLE
Sprint 7 - Revisar o termo de abertura

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#46]
# Descrição
O termo de abertura do projeto está faltando o preço do projeto.

# Tarefas
- [x] Colocar a estimativa de preço do projeto.
- [x] Revisar a escrita geral do projeto.

# Critérios de aceitação
- [ ] Documento revisado.

**Comment by Thiab394** [comment]
As mudanças estão de acordo com a estimativa de nosso projeto
