### ISSUE TITLE
Sprint 2 - Aprender GitHub Page

### ISSUE THREAD

**Issue by jpanacleto2** [fga-eps-mds/2022-1-OiaAMoeda#5]
### Descrição
Estudar o GitHub Pages e fazer ao menos um tutorial

### Tarefas

- [x] Estudar o Github Pages
- [x] Implementar ao menos um tutorial

### Validação

- [x] Compartilhar com os membros do grupo

**Comment by Eruel6** [comment]
A pesquisa e o compartilhamento foram feitos de forma satisfatória
