### ISSUE TITLE
Sprint 9 - US 07 Eu, como usuário, gostaria de visualizar os graficos relativos a cripto selecionada

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#50]
# Descrição
Esta issue tem como objetivo permitir que o usuário visualize os gráficos relacionados a cripto.

# Tarefas

- [ ]  Implementar a história de usuário.

# Critérios de aceitação
 
- [ ] História de usuário implementada e sem bugs

**Comment by jpanacleto2** [comment]
Exemplos que creio que se encaixam:

>O primeiro utiliza node.js e uma biblioteca de graficos junto com a API da binance entretanto usa react

https://www.youtube.com/watch?v=Be-VmZ1TKkg&t=1268s

> O segundo ja utiliza um widget geral bem mais facil e completo da binance entretanto eu nao sei como ele se comunicaria com o nosso servidor

https://www.youtube.com/watch?v=CN7T3MMZRqM&t=153s

> Ja o terceiro eu consegui implementar comunicando com o servidor entretanto ele e bem mais complexo de implementar todas as funcionalidades e nao consegui atualiz-lo em tempo real so quando atualiza a pagina

https://www.youtube.com/watch?v=NlHjhmIe1EI
