### ISSUE TITLE
Sprint 9 - Treinamento backend 

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#56]
# Descrição
Alguns membros ainda estão perdidos em relação ao backend do projeto, esta issue tem o objetivo de situa-los de uma forma melhor.

# Tarefas
- [x] [Vídeo sobre javascript](https://youtube.com/playlist?list=PLirko8T4cEmy3m-KziWgI-kSo6qUd1e-N)
- [x] Vídeo sobre API.
- [ ] Definição simplificada da integração do backend e frontend no projeto nos comentários desta issue.

# Critérios de aceitação
- [x] Vídeos postados nos comentários da issue.
- [x] Membros darem feedback se o backend foi entendido melhor.

**Comment by pabloheika** [comment]
https://youtube.com/playlist?list=PLirko8T4cEmy3m-KziWgI-kSo6qUd1e-N
assistam os 3 primeiros vídeos dessa play list.

**Comment by Eruel6** [comment]
Todos os membros assistiram os vídeos e possuem uma maior clareza do backend do projeto
