### ISSUE TITLE
Sprint 9 - Revisão do Diagrama de Pacotes

### ISSUE THREAD

**Issue by Osidious** [fga-eps-mds/2022-1-OiaAMoeda#57]
# Descrição
O [diagrama de pacotes](https://github.com/fga-eps-mds/2022-1-OiaAMoeda/blob/main/Docs/Documento_de_arquitetura.md) atual do projeto não explicita de forma correta a comunicação entre o back-end e o front-end da página. Essa issue tem o objetivo de corrigir esse problema.

# Tarefas
- [x] Estudar sobre a integração do NodeJs no site.
- [x] Montar um novo diagrama incuindo a relação entre as API's, o NodeJs, e o Front-end

# Critérios de aceitação
- [x] Commit da nova versão do documento.
- [x] Revisão por um outro integrante do projeto.

**Comment by Thiab394** [comment]
Diagrama de Pacotes criado e adicionado no documento de arquitetura, após estudos do node.js, express.js e de suas relações com o front e backend, aguardando revisão

**Comment by Eruel6** [comment]
Diagrama revisado e de acordo com o projeto
