### ISSUE TITLE
Sprint 9 - Reestruturação do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by Osidious** [fga-eps-mds/2022-1-OiaAMoeda#59]
# Descrição
O [protótipo de alta fidelidade](https://github.com/fga-eps-mds/2022-1-OiaAMoeda/blob/main/Docs/Prototipo_de_alta_fidelidade.md) atual e a versão inicial do site estão em disacordo. Essa issue busca igualá-los

# Tarefas
- [x] Atualizar landing page.
- [x] Atualizar a tela de notícias.
- [x] Atualizar Dashboard.

# Critérios de aceitação
- [x] Landing page criado.
- [x] Tela de notícias criada.
- [x] Dashboard criado.
- [x] Commit da nova versão do documento.
- [x] Revisão por um outro integrante do projeto.

**Comment by Eruel6** [comment]
Documento atualizado
