### ISSUE TITLE
Sprint 2 - Adicionar o Zenhub no repositório 

### ISSUE THREAD

**Issue by Eruel6** [fga-eps-mds/2022-1-OiaAMoeda#6]
# Descrição
O zenhub será uma ferramenta fundamental para o squad ter acesso a métricas importantes, com isso esta issue se destina ao inicio da utilização do mesmo no repositório.

# Tarefas
- [x] Tutorial de como baixar a extensão zenhub.
- [x] Adição do zenhub no repositório do projeto. 

# Critérios de aceitação
- [x] Todos os membros do grupo devem ter instalado a extensão do zenhub.
- [x] O zenhub deve ter estar funcionando dentro do repositório. 
- [x] Todos os membros devem ter uma noção básica de como utilizar o zenhub.

**Comment by Eruel6** [comment]
Para instalar a extensão do zenhub no chrome ou no firefox, deve se abrir as extensões do navegador e procurar por "zenhub", após isso deve se realizar a instalação da mesma e a extensão estará habilitada para uso

**Comment by jpanacleto2** [comment]
Todos os membros do Squad instalaram as dependências do zenhub e estão alocados na plataforma.
